language: java


matrix:
  include:
    - jdk: oraclejdk9
      env: compilejdk=oraclejdk9
    - jdk: oraclejdk10
      env: compilejdk=oraclejdk10
    - jdk: oraclejdk11
      env: compilejdk=oraclejdk11
    - jdk: oraclejdk12
      env: compilejdk=oraclejdk12
    - jdk: oraclejdk13
      env: compilejdk=oraclejdk13
    - jdk: oraclejdk14
      env: compilejdk=oraclejdk14
    - jdk: openjdk8
      env: compilejdk=openjdk8
    - jdk: openjdk10
      env: compilejdk=openjdk10


git:
  quiet: true
branches:
  only:
    - master

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - fs1194361820@163.com
    on_success: never
    on_failure: always
